import { useCallback, useEffect, useState } from "react";

/** Automatic timeline cards generated by other tabs and shown on the Wall. */
export type WallEventSource = "work" | "cash" | "diary" | "hours";

export type WallEvent = {
  id: string;
  source: WallEventSource;
  title: string;
  detail: string;
  createdAt: string;
};

const KEY = "myplace:events";
const CHANNEL = "myplace:events-changed";
const LIMIT = 300;

const newId = () => Math.random().toString(36).slice(2, 10) + Date.now().toString(36);

export function readEvents(): WallEvent[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = localStorage.getItem(KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? (parsed as WallEvent[]) : [];
  } catch {
    return [];
  }
}

function writeEvents(events: WallEvent[]) {
  try {
    localStorage.setItem(KEY, JSON.stringify(events.slice(0, LIMIT)));
  } catch {
    /* quota exceeded — ignore */
  }
  window.dispatchEvent(new Event(CHANNEL));
}

/** Record a timeline card from any tab. Safe to call from event handlers only. */
export function logEvent(source: WallEventSource, title: string, detail = "") {
  if (typeof window === "undefined") return;
  const event: WallEvent = {
    id: newId(),
    source,
    title,
    detail,
    createdAt: new Date().toISOString(),
  };
  writeEvents([event, ...readEvents()]);
}

/** Live list of timeline cards; updates whenever any tab logs one. */
export function useWallEvents() {
  const [events, setEvents] = useState<WallEvent[]>([]);

  useEffect(() => {
    const sync = () => setEvents(readEvents());
    sync();
    window.addEventListener(CHANNEL, sync);
    window.addEventListener("storage", sync);
    return () => {
      window.removeEventListener(CHANNEL, sync);
      window.removeEventListener("storage", sync);
    };
  }, []);

  const remove = useCallback((id: string) => {
    writeEvents(readEvents().filter((e) => e.id !== id));
  }, []);

  const clear = useCallback(() => writeEvents([]), []);

  return { events, remove, clear };
}
